---
- name: Test AOS modules
  connection: local
  hosts: all
  gather_facts: false
  environment:
    AOS_VERIFY_CERTIFICATE: False
  tasks:
    - block:
        - include_role:
            name: test_pb_aos_login
        - include_role:
            name: test_pb_aos_asn_pool
        - include_role:
            name: test_pb_aos_vni_pool
        - include_role:
            name: test_pb_aos_ip_pool
        - include_role:
            name: test_pb_aos_blueprint_deploy
      rescue:
        - name: Clean Up After Failure
          debug:
            msg: Failure detected, cleaning up and reseting environment"
        - include_role:
            name: test_clean_up_tests
        - name: Failure detected in test roles
          fail:
            msg: "Failure: {{ansible_failed_task.name}}: {{ansible_failed_result}}"
      always:
        - include_role:
            name: test_clean_up_tests
        - name: Cleaning up test roles and resetting test enviroment
          debug:
            msg: "Cleaning up after the mess. Nothing to see here, move along."
