---
- name: Test AOS modules
  connection: local
  hosts: all
  gather_facts: false
  environment:
    AOS_VERIFY_CERTIFICATE: False
  tasks:
    - block:
        - include_role:
            name: test_pb_aos_login
        - include_role:
            name: test_pb_aos_asn_pool
        - include_role:
            name: test_pb_aos_vni_pool
        - include_role:
            name: test_pb_aos_ip_pool
        - include_role:
            name: test_pb_aos_blueprint_deploy
      rescue:
        - include_role:
            name: test_clean_up_tests
        - name: Failure detected in test roles
          fail:
            msg: "Failure detected in test roles, cleaning up and reset environment"