---
- name: Test AOS modules
  connection: local
  hosts: all
  gather_facts: false
  environment:
    AOS_VERIFY_CERTIFICATE: False
  tasks:
    - block:
        - include_role:
            name: test_aos_login
        - include_role:
            name: test_aos_asn_pool
        - include_role:
            name: test_aos_vni_pool
        - include_role:
            name: test_aos_ip_pool
        - include_role:
            name: test_aos_bp_deploy
        - include_role:
            name: test_aos_bp_security_zone
        - include_role:
            name: test_aos_bp_virt_net
      rescue:
        - name: Clean Up After Failure
          debug:
            msg: Failure detected, cleaning up and reseting environment"
        - include_role:
            name: test_clean_up_tests
      always:
        - include_role:
            name: test_clean_up_tests
        - name: Cleaning up test roles and resetting test enviroment
          debug:
            msg: "Cleaning up after the mess. Nothing to see here, move along."
